// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZy-poCl4f2yQITb3irlr2JiULgGsdhqY',
    appId: '1:603598484412:web:715516a9e42a2e3293b1b9',
    messagingSenderId: '603598484412',
    projectId: 'waste-manager-ef49a',
    authDomain: 'waste-manager-ef49a.firebaseapp.com',
    storageBucket: 'waste-manager-ef49a.firebasestorage.app',
    measurementId: 'G-QK5R7K1VSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oSalTZNGOqixDiyu-xDAyRzm-a3l-g0',
    appId: '1:603598484412:android:0eab5fb80b6645c893b1b9',
    messagingSenderId: '603598484412',
    projectId: 'waste-manager-ef49a',
    storageBucket: 'waste-manager-ef49a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGevd4RAJliq492NqmiIzT0DB43Jls4V0',
    appId: '1:603598484412:ios:45803c01a1c6645093b1b9',
    messagingSenderId: '603598484412',
    projectId: 'waste-manager-ef49a',
    storageBucket: 'waste-manager-ef49a.firebasestorage.app',
    androidClientId: '603598484412-qc8cgqqikccauthovs3s0qhltuuk16ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteManager',
  );
}
